"""
Diary tools: read daily conversation diaries generated by DiaryManager.
Diary files are stored as JSON in ./data/archives/<角色名>/, named diary_YYYYMMDD.json.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict

logger = logging.getLogger(__name__)

# ── 记忆隔离：当前活跃角色名 ──────────────────────────────────────
_CHARACTER_NAME = "default"


def set_character(name: str) -> None:
    """设置当前活跃角色名，由 plugin.py 在初始化时调用。"""
    global _CHARACTER_NAME
    _CHARACTER_NAME = str(name).strip() or "default"


def _get_archive_dir() -> Path:
    """获取当前角色的归档目录路径。"""
    return Path("data/archives") / _CHARACTER_NAME


def _tool_diary_read(date_str: str) -> Dict[str, Any]:
    """
    读取指定日期的日记文件。

    Args:
        date_str: 日期字符串，格式 YYYYMMDD（如 "20260529"）

    Returns:
        日记 JSON 内容；若文件不存在则返回提示信息。
    """
    date_str = (date_str or "").strip()
    if not date_str:
        return {"error": "date_str 不能为空"}

    diary_path = _get_archive_dir() / f"diary_{date_str}.json"
    if not diary_path.exists():
        return {"message": f"没有找到 {date_str} 的日记文件", "date": date_str}

    try:
        with open(diary_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return data
    except Exception as e:
        logger.error(f"读取日记失败 {diary_path}: {e}")
        return {"error": f"读取日记失败: {e}"}


# ── 注册到 ToolManager ──────────────────────────────────────────────

def _register_diary_tools():
    try:
        from llm.tools.tool_manager import ToolManager
        tm = ToolManager()
        tm.register_function(
            _tool_diary_read,
            name="diary_read",
            group="memory",
            description=(
                "Read the diary file for a specific date (format YYYYMMDD). "
                "Returns the diary content including summary, keywords, mood, and notable_events. "
                "Use this to quickly check what happened on a given day before deciding "
                "whether to search the full conversation archives."
            ),
            risk="low",
        )
        logger.info("Diary tools registered successfully.")
    except Exception as e:
        logger.error(f"Failed to register diary tools: {e}")


_register_diary_tools()